### ISSUE TITLE
Store genre options in localStorage

### ISSUE THREAD

**Issue by glazovg** [rargotte/Watch-Chill-#13]
As a user when clicks on Next button
I want to be able to store the selected genre options in localStorage
So I can use stored data as parameters in the API call

Acc: Store genre id options from Genre options page in localStorage

Dev notes: In order to know which id matches with genre name please take a look to https://developers.themoviedb.org/3/genres/get-movie-list, API endpoint, and save ids into localStorage.

**Comment by Abimael1996** [comment]
I think I need an API key to see the list of genre names...

Can you give me the key, or is there another way to see the list? @glazovg
